name: jab_example_app
description: A new Flutter project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.24.0
  jab:
    path: ../jab

dev_dependencies:
  flutter_test:
    sdk: flutter