name: jab_example_app
description: A new Flutter project.
version: 0.0.2
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  jab:
    path: ../jab

dev_dependencies:
  flutter_test:
    sdk: flutter
