name: jab_example
description: Jab example

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  jab:
    path: ../jab
  jab_example_app:
    path: ../jab_example_app

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
