name: jab
description: A simple dependency injection framework for Flutter. It offers out-of-the-box support for the BLoC pattern.
version: 0.0.5
author: Lukasz Ciastko

environment:
    sdk: '>=2.12.0-0 <3.0.0'
    flutter: '>=1.17.0 <2.0.0'

dependencies:
    flutter:
        sdk: flutter

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
