name: jab
description: A simple hierarchical dependency injection framework for Flutter. It offers easy dependency overriding in the Widget tree and provides out-of-the-box support for the BLoC pattern.
version: 0.0.4
homepage: https://github.com/lukaszciastko/jab

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  jab_example_app:
    path: ../jab_example_app